### ISSUE TITLE
Q: Any particular reason this is implemented at Rack middleware?

### ISSUE THREAD

**Issue by jefflunt** [enova/active_record_stats#4]
When looking into [ActiveSupport::Notifications](http://guides.rubyonrails.org/active_support_instrumentation.html) it seems strange to me that the data collection code in this gem is implemented as Rack middleware, which is called on every request to Rack.

The subscriptions to `sql.active_record` and `process_action.action_controller` are long-lived, yet `lib/active_record_stats/rack_middleware.rb` subscribes and unsubscribes to these events on **every** request -- `sidekiq_server_middleware` and `resque_plugin` seem to do the same.

Am I missing something about why this is implemented as middleware? Seems like it would be better implemented as initialization code.

**Comment by Slania** [comment]
I believe this was done to tie #queries by type to a certain endpoint being hit. I think it was hard to subscribe in a "cross-cutting" way to subscribe to all sql notifications and marry them to the endpoint that spawned them.

This tie-up between controller endpoint and #queries by type is the crux of this gem, so if there is a way to keep this by not having to sub and unsub per rack action, I think we should definitely switch to that and if possible, can you please post an example of how we can do that?

**Comment by jefflunt** [comment]
Gotcha, thanks for the explanation. I'll take a look and follow up with another issue if I come up with a solution.
